config/routes.rb
ContactList::Application.routes.draw do
root 'people#index'
resources:people

end

app/models/address.rb
class Address < ActiveRecord::Base
  belongs_to :person
end

app/models/person.rb
class Person < ActiveRecord::Base
  has_one :address, dependent: :destroy
  accepts_nested_attributes_for :address

  def name
    [first_name, last_name].join(' ')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  def index
    @people = Person.all
  end

  def show
    @person = Person.find(params[:id])
    @address = @person.address
  end

  def new
    @person = Person.new
    @person.build_address
  end

  def edit
    @person = Person.find(params[:id])
    @person.build_address
  end

  def create
    @person = Person.new(person_params)

    if @person.save
      flash.notice = "User Created"
      redirect_to people_url
    else
      render 'new'
    end
  end


  def update
    @person = Person.find(params[:id])
    if @person.update(person_params)
      flash.notice = "User has been updated"
      redirect_to person_url
    else
      render "edit"
    end
  end


  def destroy
    @person = Person.find(params[:id])

    @person.destroy

    redirect_to people_url
  end

  private
  def find_user
    @person = Person.find(params[:id])
  end

  def person_params
    params.require(:person).permit(:first_name, :last_name, :phone, address_attributes: [:street_address, :city, :state, :zip])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ContactList</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/people/_form.html.erb
<%= form_for @person do |f| %>
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>
  <h3>Address</h3>
  <%= f.fields_for :address do |address_form| %>
    <div class="field">
      <%= address_form.label :street_address %>
      <%= address_form.text_field :street_address %>
    </div>
    <div class="field">
      <%= address_form.label :city %>
      <%= address_form.text_field :city %>
    </div>
    <div class="field">
      <%= address_form.label :state %>
      <%= address_form.text_field :state %>
    </div>
    <div class="field">
      <%= address_form.label :zip %>
      <%= address_form.text_field :zip %>
    </div>
  <% end %>
  <%= f.submit  %>
<% end %>

app/views/people/delete.html.erb
<h1>Delete</h1>

app/views/people/edit.html.erb
<h1>Edit User</h1>
<%= render 'form' %>

app/views/people/index.html.erb
<h2>Contact List</h2>
<table>
  <thead>
    <tr>
      <th>
      Name
      </th>
      <th>
      Phone Number
      </th>
      <th>
        City
      </th>
    </tr>
  </thead>
  <tbody>
  <% @people.each do |person| %>
    <tr>
      <td><%= person.first_name %></td>
      <td><%= person.phone %></td>
      <td>
        <% if person.address.nil? %>
        N/A
        <% else %>
        <%= person.address.city %></td>
        <% end %>
      <td><%= link_to 'Edit', edit_person_path(person) %></td>
      <td><%= link_to 'Show', person_path(person) %></td>
      <td><%= link_to 'Destroy', person_path(person), method: :delete, data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>
<%= link_to 'Create a New User', new_person_path %>

app/views/people/new.html.erb
<h1>Create a New Contact</h1>
<%= render 'form' %>

app/views/people/show.html.erb
<h1><%= @person.name %></h1>
<div>
  Phone: <%= @person.phone %>
</div>
<div>
  Address: <%= @address.street_address %>
</div>
<div>
  City: <%= @address.city %>
</div>
<div>
  State: <%= @address.state %>
</div>
<div>
  Zip: <%= @address.zip %>
</div>